---
title: "6306_CaseStudy1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(maps)
library(mapproj)
library(usmap)
library(curl)

```


## Question 1: Breweries in each state
```{r Map Breweries in Each State}
#load brewery data
#breweries <- read.csv("C:/Users/johnc45/OneDrive - Nationwide/Desktop/Working/SMU/6306 - Doing Data Science/Unit 8 and 9 Case Study 1/Breweries.csv")
breweries <- read.csv(curl("https://raw.githubusercontent.com/tricleve/6306_CaseStudy1/master/Breweries.csv"))
#Trim space in front of abbreviation
breweries$abbr = str_trim(breweries$State)
colnames(breweries)[1] = "Brewery_id"

#Generate brewery count by state
brewery_count_by_state = count(breweries,abbr)

#Clean up column name to be more descriptive
colnames(brewery_count_by_state)[2] = "Breweries"

#Merge/select brewery count with statepop (usmap data set) to get fips for plot.
plotbrew = merge(statepop,brewery_count_by_state,by = "abbr") %>% select(fips, Breweries)

#Plot brewery count on the state map.  Includes Alaska, Hawaii and DC
plot_usmap(data=plotbrew, values="Breweries", color = "black") + scale_fill_gradient(name = " Brewery Count", low = "yellow", high = "red") + labs(title="Brewery count by state", subtitle="All 50 states and DC") + theme(legend.position = "right")
```

## Question 2: Merge beer data with brewries data
```{r Merge Beer Data}
beers <- read.csv(curl("https://raw.githubusercontent.com/tricleve/6306_CaseStudy1/master/Beers.csv"))

comb_data = full_join(beers,breweries, by="Brewery_id")

tail(comb_data, 6)
head(comb_data, 6)

```


## Question 3: Address Missing Values in each column
```{r Address Combined Data Missing Values}
sum(is.na(comb_data$ABV))
sum(is.na(comb_data$IBU))
sum(is.na(comb_data$Style))

beerclean = comb_data %>% filter (!is.na(ABV) & !is.na(IBU) & !is.na(Style))

dim(comb_data)
dim(beerclean)

```

## Question 4: Plot median ABV and IBU by state
```{r Plot median ABV and IBU by state}


##The two plots below display the median ABV and IBU 
plotABV <- beerclean %>% group_by(abbr) %>% summarise(medianABV= median(ABV)) %>% arrange(desc(medianABV)) 
plotABV$abbr <- factor(plotABV$abbr, levels = plotABV$abbr)

plotABV %>% ggplot(aes(abbr,medianABV, fill=medianABV))+geom_bar(stat="identity", width=.5)+ coord_cartesian(ylim=c(.03,.07)) + scale_fill_gradient(low = "yellow", high= "red")+ labs(title="Ordered Bar Chart", subtitle="Median ABV by State") + theme(axis.text.x = element_text(angle=65, vjust=.3)) 

plotIBU <- beerclean %>% group_by(abbr) %>% summarise(medianIBU= median(IBU)) %>% arrange(desc(medianIBU)) 
plotIBU$abbr <- factor(plotIBU$abbr, levels = plotIBU$abbr)

plotIBU %>% ggplot(aes(abbr,medianIBU, fill=medianIBU))+geom_bar(stat="identity", width=.5) + scale_fill_gradient(low = "yellow", high= "red")+ labs(title="Ordered Bar Chart", subtitle="Median IBU by State") + theme(axis.text.x = element_text(angle=65, vjust=.3)) 

## The two plots below present the states alphabetically.
beerclean %>% group_by(abbr) %>% summarise(medianABV= median(ABV))%>% ggplot(aes(abbr,medianABV, fill=medianABV))+geom_bar(stat="identity", width=.5)+ coord_cartesian(ylim=c(.03,.07)) + scale_fill_gradient(low = "yellow", high= "red")+ labs(title="Median ABV by State", x="State", y="Median ABV") + theme(axis.text.x = element_text(angle=65, vjust=.3)) 

beerclean %>% group_by(abbr) %>% summarise(medianIBU= median(IBU)) %>% ggplot(aes(abbr,medianIBU, fill=medianIBU))+geom_bar(stat="identity", width=.5) + scale_fill_gradient(low = "yellow", high= "red")+ labs(title="Median IBU by State", x="State", y="Median IBU") + theme(axis.text.x = element_text(angle=65, vjust=.3)) 

```

## Question 5: Display the state with highest ABV and IBU
```{r Show states with highest ABV and IBU}

beerclean[grep(max(beerclean$ABV),beerclean$ABV),] %>% select(City, abbr, Name.y, Name.x, ABV)
beerclean[grep(max(beerclean$IBU),beerclean$IBU),] %>% select(City, abbr, Name.y, Name.x, IBU)

```

## Question 6: Comment on summary stats and distribution of ABV variable
``` {r Summary and distribution of ABV}

beerclean %>% ggplot(aes(ABV)) + geom_histogram(fill ='red', binwidth = .005) + labs(title="Distribution of ABV")
summarise(beerclean, max=max(ABV), min=min(ABV), mean = mean(ABV), median = median(ABV), sd=sd(ABV))

```
## Question 7: Scatterplot of IBU and ABV
``` {r Scatterplot IBU vs ABV}

beerclean %>% ggplot(aes(ABV, IBU)) + geom_jitter(color='red',width=.01) + labs(title="Scatterplot Bitterness vs Alcohol", x="Alcohol Content (ABV)", y="Bitterness (IBU)")

beerclean %>% ggplot(aes(ABV, IBU)) + geom_point()
```

## Question 8: KNN 
``` {r KNN to classify IPAs and Ales}

sum(str_detect(beerclean$Style,"\\bIPA\\b"))
sum(str_detect(beerclean$Style,"\\bIndia Pale Ale\\b"))

beerclean %>% filter(str_detect(beerclean$Style, "\\bIndia Pale Ale\\b") | str_detect(beerclean$Style,"//bIPA//b"))

beerIPA <- beerclean %>% filter(str_detect(Style,"\\bIPA\\b|\\bIndia Pale Ale\\b"))


```